name: CI for build and Selenium tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        run: chrome --version
      - name: Run Tests
        run: mvn -B package --file pom.xml test